# Generated by Django 5.1.4 on 2024-12-25 22:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rendezVous', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emission', models.DateTimeField(default=django.utils.timezone.now)),
                ('montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payee', models.BooleanField(default=False)),
                ('mode_paiement', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('rendezvous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='rendezVous.rendezvous')),
            ],
            options={
                'ordering': ['-date_emission'],
            },
        ),
    ]
