"""
Django settings for GestionBackend project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f1u8f&%o@i^6o96ytkge9!6_&bz6w845ola*o@26cnrjfzp&uw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []  # Ajoutez ici les hôtes autorisés en production

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',    # Pour Django REST Framework
    'users',             # App pour la gestion des utilisateurs
    'vehicules',          # App pour la gestion des véhicules
    'rendezVous',      # App pour la gestion des rendez-vous
    'factures',          # App pour la gestion des factures
    'stats',             # App pour la page de statistiques
    'corsheaders',
    'drf_yasg',
    
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # ou "http://127.0.0.1:5173" selon votre URL
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # tout en haut
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Basic': {'type' : 'basic'},
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            
        }
    },
    'LOGIN_URL' : '/admin/login/'
}







SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    # autres paramètres possibles :
    # 'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    # 'ROTATE_REFRESH_TOKENS': False,
    # etc.
}

ROOT_URLCONF = 'GestionBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Si vous avez des templates à un endroit spécifique, ajoutez le chemin dans DIRS
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GestionBackend.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'GestionRendezVous',
        'USER': 'root',
        'PASSWORD': 'Mouhamedsws7',
        'HOST': 'localhost',  # ou l'adresse IP du serveur MySQL
        'PORT': '3306',       # Port par défaut de MySQL
    }
}



STATIC_URL = '/static/'

# Emplacement où Django collectera les fichiers statiques
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Dossiers contenant des fichiers statiques locaux
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Assurez-vous que ce chemin inclut `static/swagger-ui`
]


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration de Django REST Framework et JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}
