# Generated by Django 5.1.6 on 2026-03-24 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garages", "0012_alter_organization_owner"),
        ("prestations", "0002_categorie_prestation_and_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorieprestation",
            name="garage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories_prestations",
                to="garages.organization",
            ),
        ),
    ]
