# Generated by Django 5.2.1 on 2026-03-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_specialites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('owner', 'Proprietaire'), ('client', 'Client'), ('mecanicien', 'Mécanicien')], default='client', max_length=20),
        ),
    ]
