# Generated by Django 5.1.6 on 2026-03-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garages", "0012_alter_organization_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="type_etablissement",
            field=models.CharField(
                choices=[
                    ("automobile", "Atelier et services techniques"),
                    ("multi_services", "Multi-services (prestations variees)"),
                ],
                default="multi_services",
                max_length=20,
            ),
        ),
    ]
