# Generated by Django 5.2.1 on 2026-03-20 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0006_fermetureexceptionnellegarage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceoffert',
            options={'ordering': ['ordre_affichage', 'nom']},
        ),
    ]
