# Generated by Django 5.1.4 on 2024-12-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezVous', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='estimatedTime',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Durée estimée (en heures).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='quote',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Devis (en €).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('done', 'Terminé'), ('rejected', 'Refusé')], default='pending', max_length=20),
        ),
    ]
