# Generated by Django 5.1.6 on 2026-03-24 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garages", "0012_alter_organization_owner"),
        ("rendezVous", "0013_drop_legacy_vehicules_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rendezvous",
            name="garage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rendezvous",
                to="garages.organization",
            ),
        ),
    ]
