# Generated by Django 5.1.4 on 2024-12-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezVous', '0002_rendezvous_estimatedtime_rendezvous_quote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('modification_requested', 'Modification Demandée'), ('cancelled', 'Annulé'), ('done', 'Terminé'), ('rejected', 'Refusé')], default='pending', max_length=30),
        ),
    ]
