# Generated by Codex on 2026-03-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0001_initial'),
        ('rendezVous', '0003_alter_rendezvous_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='vehicules.vehicule'),
        ),
    ]
